--CREATE PROCEDURE [dbo].[DeleteCommissionAgentExpenses]
--   @CommissionAgentExpensesId INT
--AS
--BEGIN
--		Update [CommissionAgentExpenses] set isActive=0 where [CommissionAgentExpensesId] = @CommissionAgentExpensesId
--END;