--CREATE PROCEDURE  [dbo].[GetCommissionAgentExpensesByStockInId] 
--@StockInId INT=0 
--AS
--BEGIN
--SELECT * FROM dbo.[CommissionAgentExpenses] WITH (NOLOCK) WHERE StockInId = @StockInId AND IsActive = 1;
--END;
