--CREATE PROCEDURE [dbo].[GetCommissionAgentExpensesByStockInId]
--    @StockInId INT
--AS
--BEGIN
--		SELECT * FROM [CommissionAgentExpenses] WITH (NOLOCK) WHERE [StockInId] = @StockInId AND IsActive = 1;
--END;
